### ISSUE TITLE
What changes do I need to make in config.py for running on a single CPU machine? 

### ISSUE THREAD

**Issue by aseem-thakkar** [adityabingi/DCGAN#1]

**Comment by adityabingi** [comment]
Hello aseem-thakkar,
It is not advisable to train the DCGAN model on a single CPU as it is very slow; however, if you intend to train on a single CPU, replace the distribute strategy code in dcgan.py.
i.e replace strategy = tf.distribute.MirroredStrategy (line 185) with strategy = tf.distribute.OneDeviceStrategy(device="/cpu:0")
