### ISSUE TITLE
How to save the model?

### ISSUE THREAD

**Issue by Alyetama** [adityabingi/DCGAN#3]
This is not really an issue, but how could I store the model using the [SavedModel format](https://www.tensorflow.org/guide/saved_model)? Would appreciate your thoughts! Thanks!

**Comment by adityabingi** [comment]
You can replace saving with checkpoint saver in dcgan.py with [SavedModel APIs in distribute strategies](https://www.tensorflow.org/tutorials/distribute/save_and_load);
 tf.saved_model.save(<model>, <save_path>) or directly calling using .save( ) method on both discriminator and generator models.

I am not sure if the SavedModel format works with a custom training loop as implemented in this repo, although SavedModel format saves the entire execution graph and model architecture, model state, and optimizer states; 
There seem to be having issues with retraining saved models like this one [here](https://github.com/tensorflow/tensorflow/issues/40342).

Do try and let me know if it works.

**Comment by Alyetama** [comment]
Thank you for your input!!
I managed to save and load it successfully by sub-classing the models with `tf.Module` and with some tweaks in the call function.
